### ISSUE TITLE
addition of body {user_login, user_sis_id} to user_created|updated 

### ISSUE THREAD

**Issue by robert-carroll** [ccsd/ledbelly#3]
https://community.canvaslms.com/docs/DOC-15774-payload-example-usercreated
https://community.canvaslms.com/docs/DOC-15775-payload-example-userupdated

On Wednesday October 9, these 2 events will have the `user_login` and `user_sis_id` added to the body of the event message, these 2 fields already exist in the meta data.

Keeping with other duplicate field names between meta and body, I'll be releasing an update that adds the __meta_ suffix to the field names in the meta collection.
https://github.com/ccsd/ledbelly/blob/master/src/events/canvas_raw.rb#L31 and 32

The field values sent with meta data here, are the actor (user making the change), while the body values are that of the affected user.

I plan to release:
updates to the canvas raw parser
updates to the canvas raw schema
a way to easily update your database to reflect the changes.

**Comment by robert-carroll** [comment]
Resolved:
Updated canvas raw, parser and schema
updated live_stream (custom), extension and schema

To update:
1. Stop LEDbelly
2. Update code from Repo
3. Update the database, to preserve existing data, first run the rename statements, then run the add statements. https://gist.github.com/robert-carroll/2a03d2751ec6d4a3863369b5facbc80b
4. Restart LEDbelly

**Comment by dongchuanluo** [comment]
I’m done with the following update.

Luo
